### ISSUE TITLE
Oops, teamList() goes wrong.  Please run cs-go again. If it still does not work, feel free to open an issue on https://github.com/lucaspalencia/cs-go/issues

### ISSUE THREAD

**Issue by honkkki** [lucaspalencia/cs-go#9]
Oops, teamList() goes wrong.

Please run cs-go again.
If it still does not work, feel free to open an issue on https://github.com/lucaspalencia/cs-go/issues

**Comment by lucaspalencia** [comment]
Hi @honkkki! 
What version of `cs-go` are you running ? Can you check running `cs-go --version` ?

I executed `cs-go teams` and everything works well  with the latest version `0.2.6`. 
Maybe a network problem when you executed the command ?

**Comment by honkkki** [comment]
> Hi @honkkki!
> What version of `cs-go` are you running ? Can you check running `cs-go --version` ?
> 
> I executed `cs-go teams` and everything works well with the latest version `0.2.6`.
> Maybe a network problem when you executed the command ?



> Hi @honkkki!
> What version of `cs-go` are you running ? Can you check running `cs-go --version` ?
> 
> I executed `cs-go teams` and everything works well with the latest version `0.2.6`.
> Maybe a network problem when you executed the command ?

version is 0.2.6.The problem still exist, network is ok. Can you tell me how to install it detailedly.Thx

**Comment by lucaspalencia** [comment]
@honkkki 
To install: `npm install  cs-go -g`

Could you tell me if the other commands works fine ? Like `cs-go matches` / `cs-go results` / `cs-go streams` ?

**Comment by honkkki** [comment]
> @honkkki
> To install: `npm install cs-go -g`
> 
> Could you tell me if the other commands works fine ? Like `cs-go matches` / `cs-go results` / `cs-go streams` ?

i try it in windows with cmd is ok . But when i use cs-go in git for windows will get the same error.I dont know why.
So it can use in windows with the window's cmd.Thx!
